name: ensemble_clustering
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.18.4
  - matplotlib=3.2.1
  - seaborn=0.9.0
  - pandas=1.1.5
  - scipy=1.4.1
  - scikit-learn=0.22.1
  - kmodes
  - notebook
  - cython